### ISSUE TITLE
вода...

### ISSUE THREAD

**Issue by I1Gus** [Cybersun-Industries/Radium-Build#175]
### Описание

передоз водой при её количестве более 60 в организме по единице токсинов за воду больше 60
все слаймы неуязвимы к этой фиче
причины
реалистичность (для тех кто не знал да можно умереть если выпить дофига воды прошу не пробовать)
убить зэка водой
пускай новички страдают

**Comment by DaltonDeanon** [comment]
При слишком большом количестве выпитой воды человека начинает вырывать(я проверял) и получается нужно добавить вырывание после "передоза водой".

**Comment by gitdubses** [comment]
Игра по 2D космонавтиков где клоун в главной роли, а глава службы безопасности курит радужную марихуану ботаников. В любом случае это будет супер бесполезно.
