### ISSUE TITLE
Рецепт бруизина

### ISSUE THREAD

**Issue by Mnwa282** [Cybersun-Industries/Radium-Build#183]
### Описание

Сменить с пропорций: [1]Бикаридин [1]Сахар [0.9]Литий = [2]Бруизин
На: [1]Бикаридин [1]Сахар [1] Литий = [3]Бруизин
Нынешний рецепт крайне неудобен, из-за чего им **никто** не пользуется.
Get fixed boi

**Comment by gitdubses** [comment]
Я думаю, что это сделали специально, чтобы бруизин не варили тоннами. Бруизин по себе мощный реагент, а если его увеличить, то зачем нужен будет бикаридин? Рецептами не пользуется, не из-за их рецепта, а из-за того, что многие даже о нём не знают.

**Comment by Mnwa282** [comment]
> Я думаю, что это сделали специально, чтобы бруизин не варили тоннами. Бруизин по себе мощный реагент, а если его увеличить, то зачем нужен будет бикаридин? Рецептами не пользуется, не из-за их рецепта, а из-за того, что многие даже о нём не знают.

В игре есть три производных бикаридина: Пунктураз, лациренол и бруизин
Лациренол лечит режущие, эффективнее чем бикаридин.
Пунтураз лечит колющие, эффективнее чем бикаридин.
Бруизин лечит ушиби, эффективние чем бикаридин
Только лациренол и пунктураз делаются из бикаридина и односложного соеденения CH/OH
В то время, как самый неэффетивный и наименее востребованный химикат среди данных реагентов имеет не то что сложный, а неприятный крафт с использованием дробного числа, из-за чего очень легко может получится ситуация, когда у тебя в растворе образуется опасный бритвиум, ведь при смешении бикаридина, то есть компоонента бруизина, и самого бруизина образуется именно он. И этого тяжелее избежать, чем в случае с другими производными. Ведь у пунктураза и лациренола чёткое разделение: половина бикаридина, половина соеденения водорода, в отличии от бруизина с дробным литием в составе. При этом почти нигде такие числа больше не встречаются. Почти везде строго одно - смешение реагентов в пропорциях из натуральных чисел. В то время как в крафте почти бесполезного бруизина используется рациональное. Коэффициент полезного действия от выведения рецепта бруизина низок из-за его низкой лечашей способности, специфичного применения и потенциальной опасности, ввиду синтеза бритвиума при смешении с другими химикатами подобного толка.
Говорю как человек, часто играющий на медицинских ролях.

**Comment by gitdubses** [comment]
> > Я думаю, что это сделали специально, чтобы бруизин не варили тоннами. Бруизин по себе мощный реагент, а если его увеличить, то зачем нужен будет бикаридин? Рецептами не пользуется, не из-за их рецепта, а из-за того, что многие даже о нём не знают.
> 
> В игре есть три производных бикаридина: Пунктураз, лациренол и бруизин Лациренол лечит режущие, эффективнее чем бикаридин. Пунтураз лечит колющие, эффективнее чем бикаридин. Бруизин лечит ушиби, эффективние чем бикаридин Только лациренол и пунктураз делаются из бикаридина и односложного соеденения CH/OH В то время, как самый неэффетивный и наименее востребованный химикат среди данных реагентов имеет не то что сложный, а неприятный крафт с использованием дробного числа, из-за чего очень легко может получится ситуация, когда у тебя в растворе образуется опасный бритвиум, ведь при смешении бикаридина, то есть компоонента бруизина, и самого бруизина образуется именно он. И этого тяжелее избежать, чем в случае с другими производными. Ведь у пунктураза и лациренола чёткое разделение: половина бикаридина, половина соеденения водорода, в отличии от бруизина с дробным литием в составе. При этом почти нигде такие числа больше не встречаются. Почти везде строго одно - смешение реагентов в пропорциях из натуральных чисел. В то время как в крафте почти бесполезного бруизина используется рациональное. Коэффициент полезного действия от выведения рецепта бруизина низок из-за его низкой лечашей способности, специфичного применения и потенциальной опасности, ввиду синтеза бритвиума при смешении с другими химикатами подобного толка. Говорю как человек, часто играющий на медицинских ролях.

Бритвиум делается из-за того, что человек синтезирует бикаридин и бруизин. Если пропорции бикаридина больше, чем 30 u, то будет делаться бритвиум. Бруизин лечит 7 eд ушибов за 1 u, а бикаридин же лечит 4 ед брута за 1 u. В основном, игрок получает больше ушибов, чем тех же самых порезов, вот и делаем вывод, что 0,9 лития не зря. Бруизин по себе реагент эффективный, увеличивать его до 90 u за одну варку, я думаю смысла не имеет.
