### ISSUE TITLE
М... А куда предложение писать?...

### ISSUE THREAD

**Issue by YaraYT** [Cybersun-Industries/Radium-Build#191]
### Описание

Кто-то что-то напутал, хотя нет, наверное, я тупой, но почему-то тебе перенаправляет на Бэтмена, я, конечно, знаю, что всё идёт от бэтменов. Ну почему именно на страницу Бэтмена, почему нельзя отправить это на наш?
Бэтмен - это Бекман.
![Screenshot_20240703-004356](https://github.com/Cybersun-Industries/Radium-Build/assets/100045329/b0518df4-c493-4f0c-89ba-623851a94b9c)

**Comment by YaraYT** [comment]
Не ладно пол беды. Так зачем мне жаловаться на хелпера если я хочу предложить идею?

**Comment by YaraYT** [comment]
![Screenshot_20240703-004850](https://github.com/Cybersun-Industries/Radium-Build/assets/100045329/aad9cb22-79c1-4c9f-869a-2f284e75df4a)

**Comment by freeze2222** [comment]
Исправлено.
